timeout: "3600s"

logsBucket: "gs://bfsi-policy-dev-001-cloudbuild-logs"

options:
  logging: GCS_ONLY

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - "echo Cloud Build config loaded Correctly"
